serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://localhost:4444
    # issuer: http://hydra:4444
  consent: https://fairplex-login.io:3000/consent
  login: https://fairplex-login.io:3000/login
  logout: https://fairplex-login.io:3000/logout

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      # - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis

strategies:
  scope: exact
  access_token: jwt #opaque # Use jwt for access tokens
  jwt:
    scope_claim: string
# oauth2:
#   token_hook: http://hydra-token-hook:3700/token-hook
