serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://fairplex-login.io:4444
    # issuer: http://localhost:4444
  consent: http://fairplex.io:8884/consent
  login: http://fairplex.io:8884/login
  logout: http://fairplex.io:8884/logout

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      # - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis

strategies:
  scope: exact
  access_token: jwt #opaque # Use jwt for access tokens
  jwt:
    scope_claim: string
# oauth2:
#   token_hook: http://hydra-token-hook:3700/token-hook
