# docker-compose -f auth-pilot-compose.yml up --force-recreate -d

services:

  nginx:
    image: nginx:latest
    ## Either use host network mode or uncomment the following line
    ports:
     - "80:80"
     - "443:443"
     - "4444:4444"
     - "4445:4445"
     - "3000:3000"
     - "4455:4455"
     - "4433:4433"
     - "4434:4434"
    #  - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      # Uncomment the following line if you want to use password protection
      # - ./auth:/etc/nginx/auth
    restart: always
    networks:
      - intranet

  fairplex-client-app:
    image: fairplex-client:0.1
    environment:
      - HYDRA_URL=http://hydra:4444
      - HYDRA_CLIENT_ID=FAIRplex
      - HYDRA_CLIENT_SECRET=secret
      - OAUTH_CALLBACK=http://fairplex.io/callback
      - AUTH_PILOT_TOKEN_EXCHANGE_URL=http://fairplex-token-exchange:8000/token-exchange
      - AMP_PD_DRS_URI=http://auth-pilot-amp-pd-visa-issuer:7000/drs/v1/objects/auth-pilot-test-data/test-data.txt
      - AUTH_PILOT_DATA_TRANSFER_URL=http://auth-pilot-data-transfer:7100/transfer
      - AMP_PD_DESTINATION_URI=gs://auth-pilot-test-data/download
    expose:
      - "5554:5554"
    restart: unless-stopped
    depends_on:
      hydra:
        condition: service_healthy
    container_name: fairplex-client-app
    networks:
      - intranet


  # Hydra ##
      # --skip-consent
  fairplex-oidc-client:
    image: oryd/hydra:latest
    command: >
      create client --endpoint http://hydra:4445
      --id FAIRplex
      --secret secret
      --grant-type authorization_code,refresh_token
      --response-type code,id_token
      --format json
      --scope openid,profile,email,ga4gh_passport_v1
      --token-endpoint-auth-method client_secret_post
      --redirect-uri http://fairplex.io/callback
    depends_on:
      hydra:
        condition: service_healthy
    restart: no
    networks:
      - intranet

  hydra:
    image: oryd/hydra:latest
    expose:
      - "80:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra-fairplex.yml all --dev
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/hydra
        target: /etc/config/hydra
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: unless-stopped
    healthcheck:
      test: "wget -qO- http://hydra:4444/health/ready || exit 1"
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 5s
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully
    networks:
      - intranet
    container_name: hydra

  hydra-migrate:
    image: oryd/hydra:latest
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate -c /etc/config/hydra/hydra-fairplex.yml sql -e --yes
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/hydra
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - intranet

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - intranet
  
  ## Kratos ##

  kratos-migrate:
    image: oryd/kratos:latest
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:latest
    expose:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/kratos
        target: /etc/config/kratos
    networks:
      - intranet
    container_name: kratos
  
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:local
    expose:
      - "3000:3000"
    environment:
      - PORT=3000
      - HYDRA_ADMIN_URL=http://hydra:4445
      - KRATOS_PUBLIC_URL=http://kratos:4433
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KRATOS_BROWSER_URL=https://fairplex-login.io:4433
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=cookie_name
      - CSRF_COOKIE_SECRET=changeme
      - DANGEROUSLY_DISABLE_SECURE_CSRF_COOKIES=false
    networks:
      - intranet

  passport-ui-node:
    image: ga4gh/ga4gh-starter-kit-passport-ui-node:local #0.0.1
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_BROWSER_URL=https://fairplex-login.io:4433
      - PASSPORT_BROKER_PUBLIC_URL=http://passport-broker.ga4gh.org:4500/ga4gh/passport/v1/ 
      - PASSPORT_BROKER_ADMIN_URL=http://passport-broker.ga4gh.org:4501/admin/ga4gh/passport/v1/ 
    expose:
      - "4455:4455"
    restart: unless-stopped
    networks:
      - intranet
    container_name: passport-ui-node

  # mailslurper:
  #   image: oryd/mailslurper:latest-smtps
  #   ports:
  #     - "4436:4436"
  #     - "4437:4437"
  #   networks:
  #     - intranet
  
  ## Passports ##

  # passport-broker:
  #   image: ga4gh/ga4gh-starter-kit-passport-broker:0.0.2
  #   ports:
  #     - '4500:4500' # public
  #     - '4501:4501' # admin
  #   networks:
  #     - intranet
  #   hostname: passport-broker.ga4gh.org


  fairplex-token-exchange:
    image: fairplex-token-exchange:0.1
    expose:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      hydra:
        condition: service_healthy
    environment:
      - HYDRA_URL=http://hydra:4444
      - HYDRA_ADMIN_URL=http://hydra:4445
      - KRATOS_ADMIN_URL=http://kratos:4434
      - AMP_PD_VISA_ISSUER_URL=http://auth-pilot-amp-pd-visa-issuer:7000
    networks:
      - intranet
    container_name: fairplex-token-exchange
  
  auth-pilot-amp-pd-visa-issuer:
    image: auth-pilot-amp-pd-visa-issuer:0.1
    volumes:
      - /Users/haduong/Downloads/auth-spike-445014-d6cebb32a765.json:/app/service-account-key.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    expose:
      - "7000:7000"
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000"]
    networks:
      - intranet
    container_name: auth-pilot-amp-pd-visa-issuer

  auth-pilot-data-transfer:
    image: auth-pilot-data-transfer:0.1
    expose:
      - "7100:7100"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=auth-spike
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7100"]
    restart: unless-stopped
    networks:
      - intranet
    container_name: auth-pilot-data-transfer

networks:
  intranet:
    driver: bridge

volumes:
  hydra-sqlite:
  kratos-sqlite:
