apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: "fairplex-authpilot-amp-pd"
  labels:
    cloud.googleapis.com/location: "us-central1"
  annotations:
    # Required to use Cloud Run multi-containers (preview feature)
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/description: "FAIRplex Auth Pilot AMP PD service"
    # Externally available
    run.googleapis.com/ingress: all
    # Disable Cloud Run invoker IAM check
    run.googleapis.com/invoker-iam-disabled: "true"
    run.googleapis.com/minScale: "0"
spec:
  template:
    metadata:
      annotations:
        # Defines container startup order within multi-container service.
        # Below requires fairplex-client-app container to spin up before nginx container,
        # which depends on the fairplex-client-app container.
        # https://cloud.google.com/run/docs/configuring/containers#container-ordering
        run.googleapis.com/container-dependencies: "{nginx: [auth-pilot-terra-api]}"
        # Execution environment Gen1 for fast cold starts
        run.googleapis.com/execution-environment: gen1
    spec:
      serviceAccountName: auth-pilot-service-account@auth-spike-445014.iam.gserviceaccount.com
      containers:
        # A) Serving ingress container "nginx" listening at PORT 8080
        # Main entrypoint of multi-container service.
        # Source is stored in nginx_config secret in Secret Manager.
        # Any pings to this container will proxy over to fairplex-client-app container at PORT 8888.
        # https://cloud.google.com/run/docs/container-contract#port
        - image: nginx
          name: nginx
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          # Referencing declared volume below,
          # Declaring volume to mount in current ingress container's filesystem
          # https://cloud.google.com/run/docs/reference/rest/v2/Container#volumemount
          volumeMounts:
            - name: nginx-conf-secret-amp-pd
              readOnly: true
              mountPath: /etc/nginx
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080

        - image: us-central1-docker.pkg.dev/auth-spike-445014/auth-pilot/auth-pilot-terra-api:1
          name: auth-pilot-terra-api
          env:
            - name: FIRECLOUD_API_URL
              value: https://api.firecloud.org/api/groups
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 5000
      
        - image: us-central1-docker.pkg.dev/auth-spike-445014/auth-pilot/auth-pilot-amp-pd-visa-issuer:0.1
          name: auth-pilot-amp-pd-visa-issuer
          env:
            - name: MY_PORT
              value: "7010"
            - name: HOSTNAME
              value: https://fairplex-authpilot-amp-pd-300966974972.us-central1.run.app/amp-pd-visa
            - name: AMP_PD_AUTH_URL
              value: http://localhost:5000/api/group/authpilot
            - name: SERVICE_ACCOUNT
              value: auth-pilot-service-account@auth-spike-445014.iam.gserviceaccount.com
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 7010
              
      # Named volumes pointing to
      # secrets in Secret Manager
      volumes:
        - name: nginx-conf-secret-amp-pd
          secret:
            secretName: nginx_config_amp_pd
            items:
              - key: latest
                path: nginx.conf
