services:
  amp-pd:
    build:
      context: ./amp-pd-service
    ports:
      - "8001:8080"
    environment:
      - DATABASE_URL=sqlite:///./pd.db
    volumes:
      - ./amp-pd-service:/app
      - ./amp-pd-service/pd.db:/app/pd.db
    command: fastapi dev main.py --host 0.0.0.0 --port 8080

  amp-ad:
    build:
      context: ./amp-ad-service
    ports:
      - "8002:8080"
    environment:
      - DATABASE_URL=sqlite:///./ad.db
    volumes:
      - ./amp-ad-service:/app
      - ./amp-ad-service/ad.db:/app/ad.db
    command: fastapi dev main.py --host 0.0.0.0 --port 8080

  sysbio:
    build:
      context: ./sysbio-service
    ports:
      - "8000:8080"
    env_file:
      - ./sysbio-service/.env
    environment:
      - DATABASE_URL=sqlite:///./sysbio.db
    volumes:
      - ./sysbio-service:/app
      - ./sysbio-service/sysbio.db:/app/sysbio.db
    command: fastapi dev main.py --host 0.0.0.0 --port 8080

  auth:
    build:
      context: ./auth-service
    ports:
      - "8003:8080"
    volumes:
      - ./auth-service:/app
    command: fastapi dev main.py --host 0.0.0.0 --port 8080
