apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra-configmap
data:
  hydra-config.yml: |
    serve:
      cookies:
        same_site_mode: Lax

    urls:
      self:
        issuer: http://hydra
      consent: https://fairplex.io/consent
      login: https://fairplex.io/kratos/self-service/login/browser
      logout: https://fairplex.io/logout


    secrets:
      system:
        - youReallyNeedToChangeThis

    oidc:
      subject_identifiers:
        supported_types:
          # - pairwise
          - public
        pairwise:
          salt: youReallyNeedToChangeThis

    strategies:
      scope: exact
      access_token: jwt
      jwt:
        scope_claim: string
